#!/usr/bin/env python3
"""
enricher.py
-----------
For each UNKNOWN gap in parse_report.json:
  1. Fuzzy-match the cleaned name against USDA SR Legacy bulk data (local CSV)
  2. Fuzzy-match against GroceryDB Harvard CSV
  3. Fall back to live USDA FDC API (requires USDA_API_KEY env var)

If a match is found with confidence ≥ 0.85, emits a proposal:
  - New nutrition_db.json entry        (if ingredient is truly new)
  - New synonyms.json entry            (if ingredient maps to an existing key)

Proposals land in proposals.json for autotune.py to apply.

Usage:
  python autotune/enricher.py
  python autotune/enricher.py --report parse_report.json --out proposals.json
  python autotune/enricher.py --max-gaps 500

Data files (download once, checked in or cached locally):
  autotune/data/usda_sr_legacy.csv    (USDA SR Legacy, ~9k entries)
  autotune/data/grocerydb.csv         (GroceryDB Harvard, ~3k entries)

USDA SR Legacy download:
  https://fdc.nal.usda.gov/download-datasets.html  → SR Legacy, CSV
GroceryDB download:
  https://github.com/GLambard/GroceryDB  → data/GroceryDB_foods.csv
"""

import argparse
import csv
import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Optional

import requests
from rapidfuzz import fuzz, process

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
REPO_ROOT  = SCRIPT_DIR.parent        # cravebox-nutrition/
DATA_DIR_ROOT = REPO_ROOT / "data"   # cravebox-nutrition/data/

DB_FILE = DATA_DIR_ROOT / "nutrition_db.json"
SYNONYMS_FILE = DATA_DIR_ROOT / "synonyms.json"
DEFAULT_REPORT = SCRIPT_DIR / "parse_report.json"
DEFAULT_OUT = SCRIPT_DIR / "proposals.json"

DATA_DIR = SCRIPT_DIR / "data"
# Compact pre-built lookup (generated by build_usda_compact.py, committed to repo)
USDA_COMPACT_JSON = DATA_DIR / "usda_compact.json"
# FDC multi-file format (local only, too large for GitHub — fallback)
USDA_FOOD_CSV     = DATA_DIR / "usda_sr_legacy.csv"
USDA_NUTRIENT_CSV = DATA_DIR / "nutrient.csv"
USDA_FN_CSV       = DATA_DIR / "food_nutrient.csv"
GROCERYDB_CSV     = DATA_DIR / "grocerydb.csv"

USDA_FDC_API = "https://api.nal.usda.gov/fdc/v1"
CONFIDENCE_THRESHOLD = 0.85

# nutrient_nbr values we want (from nutrient.csv nutrient_nbr column)
NUTRIENT_NBR_MAP = {
    "kcal": "208",   # Energy (kcal)
    "p":    "203",   # Protein
    "c":    "205",   # Carbohydrate, by difference
    "f":    "204",   # Total lipid (fat)
    "fb":   "291",   # Fiber, total dietary
    "sg":   "269",   # Sugars, total
    "na":   "307",   # Sodium, Na
}
# Keep for FDC API fallback
NUTRIENT_MAP = NUTRIENT_NBR_MAP


# ── Data loading ──────────────────────────────────────────────────────────────

def load_db() -> dict:
    return json.loads(DB_FILE.read_text(encoding="utf-8"))


def load_synonyms() -> dict:
    if SYNONYMS_FILE.exists():
        return json.loads(SYNONYMS_FILE.read_text(encoding="utf-8"))
    return {}


def load_usda_sr() -> list[dict]:
    """
    Load USDA data. Tries usda_compact.json first (fast, committed to repo),
    falls back to raw CSVs if only available locally.
    """
    # ── Fast path: compact JSON (committed to GitHub) ──────────────────────────
    if USDA_COMPACT_JSON.exists():
        print(f"    Loading USDA compact JSON ...")
        data = json.loads(USDA_COMPACT_JSON.read_text(encoding="utf-8"))
        entries = []
        for name, nutrients in data.items():
            entries.append({
                "name":   name,
                "kcal":   nutrients.get("kcal", 0.0),
                "p":      nutrients.get("p",    0.0),
                "c":      nutrients.get("c",    0.0),
                "f":      nutrients.get("f",    0.0),
                "fb":     nutrients.get("fb",   0.0),
                "sg":     nutrients.get("sg",   0.0),
                "na":     nutrients.get("na",   0.0),
                "source": "usda_compact",
            })
        print(f"    {len(entries):,} entries loaded from usda_compact.json")
        return entries

    # ── Slow path: raw CSVs (local only, 1.7 GB) ──────────────────────────────
    if not USDA_FOOD_CSV.exists():
        return []

    print("    Loading SR Legacy food names (raw CSV) ...")
    sr_foods: dict[str, str] = {}
    with open(USDA_FOOD_CSV, encoding="utf-8", errors="replace") as f:
        for row in csv.DictReader(f):
            if row.get("data_type", "").strip('"') == "sr_legacy_food":
                fdc_id = row.get("fdc_id", "").strip('"')
                desc   = row.get("description", "").strip('"').lower()
                if fdc_id and desc:
                    sr_foods[fdc_id] = desc
    print(f"    {len(sr_foods):,} SR Legacy foods found")

    if not sr_foods:
        return []

    nbr_to_key = {v: k for k, v in NUTRIENT_NBR_MAP.items()}
    nutrient_id_to_key: dict[str, str] = {}
    if USDA_NUTRIENT_CSV.exists():
        with open(USDA_NUTRIENT_CSV, encoding="utf-8", errors="replace") as f:
            for row in csv.DictReader(f):
                nid  = row.get("id", "").strip('"')
                nbrr = row.get("nutrient_nbr", "").strip('"').strip(".0")
                key  = nbr_to_key.get(nbrr)
                if key:
                    nutrient_id_to_key[nid] = key

    print("    Streaming food_nutrient.csv (this may take a moment) ...")
    food_nutrients: dict[str, dict] = {fid: {} for fid in sr_foods}
    with open(USDA_FN_CSV, encoding="utf-8", errors="replace") as f:
        for row in csv.DictReader(f):
            fdc_id      = row.get("fdc_id", "").strip('"')
            nutrient_id = row.get("nutrient_id", "").strip('"')
            amount_str  = row.get("amount", "").strip('"')
            if fdc_id not in food_nutrients:
                continue
            key = nutrient_id_to_key.get(nutrient_id)
            if key:
                food_nutrients[fdc_id][key] = _safe_float(amount_str)

    entries: list[dict] = []
    for fdc_id, name in sr_foods.items():
        nutrients = food_nutrients.get(fdc_id, {})
        entries.append({
            "name":   name,
            "kcal":   nutrients.get("kcal", 0.0),
            "p":      nutrients.get("p",    0.0),
            "c":      nutrients.get("c",    0.0),
            "f":      nutrients.get("f",    0.0),
            "fb":     nutrients.get("fb",   0.0),
            "sg":     nutrients.get("sg",   0.0),
            "na":     nutrients.get("na",   0.0),
            "source": "usda_sr",
        })
    return entries


def load_grocerydb(csv_path: Path) -> list[dict]:
    """
    Load GroceryDB Harvard CSV.
    Expected columns: food_name, energy_kcal, protein_g, fat_g, carb_g,
                      fiber_g, sugar_g, sodium_mg  (per 100g)
    """
    if not csv_path.exists():
        return []

    entries = []
    with open(csv_path, encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                entries.append({
                    "name": row.get("food_name", "").lower().strip(),
                    "kcal": _safe_float(row.get("energy_kcal")),
                    "p":    _safe_float(row.get("protein_g")),
                    "c":    _safe_float(row.get("carb_g")),
                    "f":    _safe_float(row.get("fat_g")),
                    "fb":   _safe_float(row.get("fiber_g")),
                    "sg":   _safe_float(row.get("sugar_g")),
                    "na":   _safe_float(row.get("sodium_mg")),
                    "source": "grocerydb",
                })
            except Exception:
                continue
    return entries


def _safe_float(val) -> float:
    try:
        return round(float(str(val).replace(",", "").strip()), 1)
    except (TypeError, ValueError):
        return 0.0


# ── USDA FDC API fallback ─────────────────────────────────────────────────────

def query_fdc_api(query: str, api_key: str, timeout: int = 10) -> Optional[dict]:
    """Query USDA FDC API for a food item. Returns our nutrition schema dict or None."""
    if not api_key:
        return None

    try:
        r = requests.get(
            f"{USDA_FDC_API}/foods/search",
            params={"query": query, "api_key": api_key, "pageSize": 3, "dataType": "SR Legacy,Foundation"},
            timeout=timeout,
        )
        r.raise_for_status()
        foods = r.json().get("foods", [])
    except Exception:
        return None

    if not foods:
        return None

    food = foods[0]
    nutrients = {str(n["nutrientNumber"]): n.get("value", 0) for n in food.get("foodNutrients", [])}

    return {
        "kcal": round(float(nutrients.get(NUTRIENT_MAP["kcal"], 0)), 1),
        "p":    round(float(nutrients.get(NUTRIENT_MAP["p"], 0)), 1),
        "c":    round(float(nutrients.get(NUTRIENT_MAP["c"], 0)), 1),
        "f":    round(float(nutrients.get(NUTRIENT_MAP["f"], 0)), 1),
        "fb":   round(float(nutrients.get(NUTRIENT_MAP["fb"], 0)), 1),
        "sg":   round(float(nutrients.get(NUTRIENT_MAP["sg"], 0)), 1),
        "na":   round(float(nutrients.get(NUTRIENT_MAP["na"], 0)), 1),
    }


# ── Fuzzy matching ────────────────────────────────────────────────────────────

def fuzzy_match(query: str, corpus: list[dict], threshold: float = CONFIDENCE_THRESHOLD) -> Optional[tuple[dict, float]]:
    """
    Match query against USDA corpus entries by name.

    USDA names are verbose ("nuts, cashew nuts, dry roasted, without salt added") so
    we use a two-stage approach:
      1. Pre-filter: only keep entries where ALL meaningful query words (len>2) appear
         in the USDA name — eliminates false positives like "liquid smoke" → "chocolate liquid"
      2. Among filtered candidates, score with WRatio (balanced) and return best.

    Falls back to full corpus WRatio search at a higher threshold if pre-filter returns nothing.
    """
    if not corpus:
        return None

    query_words = [w for w in query.lower().split() if len(w) > 2]

    # Stage 1: pre-filter to candidates containing ALL query words
    filtered = [e for e in corpus if all(w in e["name"] for w in query_words)]

    if filtered:
        names = [e["name"] for e in filtered]
        result = process.extractOne(query, names, scorer=fuzz.WRatio)
        if result:
            best_name, score, idx = result
            confidence = score / 100.0
            if confidence >= threshold:
                return filtered[idx], confidence

    # Stage 2: fallback — full corpus WRatio at stricter threshold
    names = [e["name"] for e in corpus]
    result = process.extractOne(query, names, scorer=fuzz.WRatio)
    if result:
        best_name, score, idx = result
        confidence = score / 100.0
        if confidence >= max(threshold, 0.92):   # stricter to avoid false positives
            return corpus[idx], confidence

    return None


def find_existing_key(query: str, db: dict, threshold: float = CONFIDENCE_THRESHOLD) -> Optional[tuple[str, float]]:
    """Check if query maps to an existing DB key with high confidence."""
    result = process.extractOne(query, list(db.keys()), scorer=fuzz.token_sort_ratio)
    if not result:
        return None
    best_key, score, _ = result
    confidence = score / 100.0
    if confidence >= threshold:
        return best_key, confidence
    return None


# ── Key validation ────────────────────────────────────────────────────────────

# Equipment and non-food terms that should never be DB keys
_EQUIPMENT_WORDS = {
    'thermometer', 'mill', 'blender', 'processor', 'mixer', 'grinder',
    'strainer', 'colander', 'skillet', 'saucepan', 'stockpot', 'wok',
    'spatula', 'whisk', 'tongs', 'ladle', 'peeler', 'zester', 'mandoline',
    'brush', 'mallet', 'twine', 'cheesecloth', 'foil', 'parchment',
}
_INVALID_KEY_RE = re.compile(
    r'^\d'                          # starts with digit (quantity fragment)
    r'|^(a|an|the)\s'              # starts with article
    r'|\bor\b'                     # "X or Y" alternative ingredients
    r'|[*†‡#@]'                    # stray special characters
    r'|\bfilled\s+with\b'          # "a spray bottle filled with"
    r'|\band\s+\w+-fry\b'          # "food mill and deep-fry ..."
    , re.I
)

def _is_valid_key(name: str) -> bool:
    """Return False for keys that are quantity fragments, equipment, or malformed phrases."""
    if _INVALID_KEY_RE.search(name):
        return False
    words = set(name.lower().split())
    if words & _EQUIPMENT_WORDS:
        return False
    if len(name.split()) > 6:   # too long to be a useful ingredient key
        return False
    return True


# ── Proposal generation ───────────────────────────────────────────────────────

def enrich_gap(cleaned_name: str, examples: list[str], db: dict, synonyms: dict,
               usda_corpus: list[dict], grocery_corpus: list[dict],
               api_key: str) -> Optional[dict]:
    """
    Try to enrich one gap. Returns a proposal dict or None.
    """
    query = cleaned_name

    # First check: does this map to an existing DB key? → synonym proposal
    existing = find_existing_key(query, db, threshold=0.90)
    if existing:
        existing_key, conf = existing
        if existing_key != query:  # avoid self-referential synonyms
            return {
                "type": "synonym",
                "alias": cleaned_name,
                "canonical": existing_key,
                "confidence": round(conf, 3),
                "source": "fuzzy_existing_key",
            }

    # Try USDA SR Legacy
    match = fuzzy_match(query, usda_corpus)
    if match:
        entry, conf = match
        nutrition = {k: entry[k] for k in ("kcal", "p", "c", "f", "fb", "sg", "na")}
        return {
            "type": "new_entry",
            "key": cleaned_name,
            "nutrition": nutrition,
            "confidence": round(conf, 3),
            "source": f"usda_sr:{entry['name']}",
        }

    # Try GroceryDB
    match = fuzzy_match(query, grocery_corpus)
    if match:
        entry, conf = match
        nutrition = {k: entry[k] for k in ("kcal", "p", "c", "f", "fb", "sg", "na")}
        return {
            "type": "new_entry",
            "key": cleaned_name,
            "nutrition": nutrition,
            "confidence": round(conf, 3),
            "source": f"grocerydb:{entry['name']}",
        }

    # Fallback: USDA FDC API
    if api_key:
        nutrition = query_fdc_api(query, api_key)
        if nutrition and nutrition.get("kcal", 0) > 0:
            return {
                "type": "new_entry",
                "key": cleaned_name,
                "nutrition": nutrition,
                "confidence": 0.85,  # API results assumed min threshold
                "source": "usda_fdc_api",
            }
        time.sleep(0.5)  # rate limit courtesy

    return None


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="CraveBox nutrition enricher")
    parser.add_argument("--report", default=str(DEFAULT_REPORT), help="parse_report.json path")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Output proposals.json path")
    parser.add_argument("--max-gaps", type=int, default=1000, help="Max gaps to process (default 1000)")
    parser.add_argument("--threshold", type=float, default=CONFIDENCE_THRESHOLD,
                        help=f"Min confidence to emit proposal (default {CONFIDENCE_THRESHOLD})")
    args = parser.parse_args()

    report_path = Path(args.report)
    if not report_path.exists():
        sys.exit(f"ERROR: report not found: {report_path}")

    print("=== CraveBox Nutrition Enricher ===")

    db = load_db()
    synonyms = load_synonyms()
    api_key = os.environ.get("USDA_API_KEY", "")

    print(f"Loading USDA data from {DATA_DIR} ...")
    usda_corpus = load_usda_sr()
    if not usda_corpus:
        print("  WARNING: usda_compact.json not found and raw CSVs unavailable.")
        print("  Run: python autotune/build_usda_compact.py  then commit the output.")

    print(f"Loading GroceryDB from {GROCERYDB_CSV} ...")
    grocery_corpus = load_grocerydb(GROCERYDB_CSV)
    print(f"  {len(grocery_corpus):,} entries loaded" if grocery_corpus else "  WARNING: not found — download from https://github.com/GLambard/GroceryDB")

    if not usda_corpus and not grocery_corpus and not api_key:
        print("  WARNING: No local data files and no USDA_API_KEY. Set USDA_API_KEY env var for API fallback.")

    report = json.loads(report_path.read_text(encoding="utf-8"))
    gaps = report.get("unknown_gaps", [])
    gaps = gaps[: args.max_gaps]
    print(f"Processing {len(gaps):,} unknown gaps ...")

    proposals: list[dict] = []
    skipped = 0

    for gap in gaps:
        cleaned_name = gap["cleaned_name"]
        if not cleaned_name or len(cleaned_name) < 2 or not _is_valid_key(cleaned_name):
            skipped += 1
            continue

        proposal = enrich_gap(
            cleaned_name=cleaned_name,
            examples=gap.get("examples", []),
            db=db,
            synonyms=synonyms,
            usda_corpus=usda_corpus,
            grocery_corpus=grocery_corpus,
            api_key=api_key,
        )

        if proposal and proposal["confidence"] >= args.threshold:
            proposal["gap_count"] = gap.get("count", 1)
            proposals.append(proposal)
        else:
            skipped += 1

    proposals.sort(key=lambda x: -x.get("gap_count", 1))

    new_entries = sum(1 for p in proposals if p["type"] == "new_entry")
    new_synonyms = sum(1 for p in proposals if p["type"] == "synonym")

    print(f"\nProposals generated:")
    print(f"  New DB entries: {new_entries:,}")
    print(f"  New synonyms:   {new_synonyms:,}")
    print(f"  Skipped:        {skipped:,}")

    out = {
        "summary": {
            "gaps_processed": len(gaps),
            "proposals": len(proposals),
            "new_entries": new_entries,
            "new_synonyms": new_synonyms,
            "skipped": skipped,
        },
        "proposals": proposals,
    }

    out_path = Path(args.out)
    out_path.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n  Proposals → {out_path}")
    print("=== Done ===")


if __name__ == "__main__":
    main()
